## Nome: João Vitor de Freitas Barbosa
### DRE: 117055449

# <center>Tarefa 4</center>

In [113]:
#y(i+1) = y(i)+ h*y'(i) pelo método
function euler(y0,x0,h, fd)
    k = x0
    y = y0
    while k < 1
        y = y + h*fd(k, y) #Aplicando euler
        k = k + h #incrementando de h
    end
    return y
end

euler (generic function with 1 method)

### Questão 1: 
a) **y'(x) = y(x) com y(0)=1**

In [8]:
#letra a
fd(x, y) = y
euler(1, 0, 0.1, fd)

2.8531167061100002

b) **y'(x) = y(x)²x com y(0)=1**

In [9]:
#letra b
fd(x, y) = y^2*x
euler(1, 0, 0.1, fd)

2.0062389840082506

### Questão 2: 
Implemente uma função em Julia tal que  
a) Entrada: os pontos(x0, y0),(x1,y1),(x2,y2) e (x3,y3)  
b) Saída: os 4 coeficientes do polinômio P(x) de grau 3 tal que P(xi) = yi

In [28]:
using LinearAlgebra

In [141]:
#Questão 2
function vandermonde((x0,y0),(x1,y1),(x2,y2),(x3,y3))
    xs = [
            [1 x0 x0^2 x0^3];
            [1 x1 x1^2 x1^3];
            [1 x2 x2^2 x2^3];
            [1 x3 x3^2 x3^3];
        ]
    ys = [[y0],[y1],[y2],[y3]]
    print(xs)
    print("\n")
    print(ys)
    print("\n")
    print(xs\ys)
end



vandermonde (generic function with 1 method)

In [104]:
vandermonde((2,3),(5,12),(7,20),(8,25))

[-2.555555555555549, 2.911111111111106, -0.11111111111111002, 0.02222222222222215]

In [140]:
using LinearAlgebra
x0 = 2 
y0 = 3
x1 = 5
y1 = 12
x2 = 7
y2 = 20
x3 = 8
y3 = 25
#prova de corretude
entrada = [(2,3),(5,12),(7,20),(8,25)]
#entrada = [1,23,3]
xs = zeros(length(entrada), length(entrada))
ys = zeros(length(entrada))
for k= 1: length(entrada)
    xn,yn = entrada[k]
    linha = []
    for i = 0:length(entrada)-1
        xs[k, i+1] = xn^i
    end
    ys[k] = yn
end
#xs
saida = xs\ys
print(saida)

[-2.555555555555549, 2.911111111111106, -0.11111111111111002, 0.02222222222222215]

### Questão 3:
Generalize o item anterior para a função poder receber n pontos

In [128]:
#Questão 3
function vandermonde_xn(entrada)
    xs = zeros(length(entrada), length(entrada))
    ys = zeros(length(entrada))
    for k= 1: length(entrada)
        xn,yn = entrada[k]
        linha = []
        for i = 0:length(entrada)-1
            xs[k, i+1] = xn^i
        end
        ys[k] = yn
    end
    a = xs\ys
    return a
end

vandermonde_xn (generic function with 1 method)

In [139]:
saida = vandermonde_xn([(2,3),(5,12),(7,20),(8,25)])
print(saida)

[-2.555555555555549, 2.911111111111106, -0.11111111111111002, 0.02222222222222215]

### Questão 4:
Dado o PVC y''(x) = 4x com y(0) = 5 e y(10) = 20
a) Monte o sistema linear que aproxima pelo método de diferenças finitas com 6 intervalos na discretização  
b) Resolva o sistema linear obtido no item anterior no Julia  
c) Use a função de interpolação para descobrir y(3.2345)

In [138]:
#Questão 4
ddy(x) = 4x
y0 = 5
y10 = 20
h = 10/6
K = [
    -2 1 0 0 0 0;
    1 -2 1 0 0 0;
    0 1 -2 1 0 0;
    0 0 1 -2 1 0;
    0 0 0 1 -2 1;
    0 0 0 0 1 -2
]
l = [
    ddy(h)*2*h - y0;
    ddy(h*2)*2*h;
    ddy(h*3)*2*h;
    ddy(h*4)*2*h;
    ddy(h*5)*2*h;
    ddy(h*6)*2*h - y10;
]
y = K\l

6-element Vector{Float64}:
 -170.63492063492063
 -324.04761904761904
 -433.015873015873
 -475.3174603174604
 -428.73015873015885
 -271.0317460317461

### Questão 5:
Resolva os seguintes exercícios da apostila do Collier com polinômios de Lagrange e também com a sua função da questão 2  
a) Exercício 1 pag109  
b) Exercício 2 pag109  
c) Exercício 3 pag109  

In [130]:
#a)
entrada = [(-1.2, -5.76),(0.3, -5.61), (1.1, -3.69)]
vandermonde_xn(entrada)

3-element Vector{Float64}:
 -6.0
  1.0
  1.0000000000000004

In [136]:
#b)
entrada = [(0.0, 1.225),(3.0, 0.905), (6.0, 0.652)]
vandermonde_xn(entrada)

3-element Vector{Float64}:
  1.225
 -0.11783333333333336
  0.0037222222222222257

In [135]:
#c)
entrada = [(0.8,cos(0.8)),(0.9,cos(0.9)),(1.0,cos(1.0)),(1.1,cos(1.1)),(1.2,cos(1.2)),(1.3,cos(1.3))]
saida = vandermonde_xn(entrada)
funcao_interpolada(x) = a[1]+a[2]x+a[3]x^2+a[4]x^3+a[5]x^4+a[6]x^5
funcao_interpolada(1.07)

0.48012422704985785

### Questão 6:
Exercício 2a e 2b da apostila do Collier

In [134]:
#2a
ddy(x) = -x
u0 = 0
u1 = 1
h = 10/6
K = [
    -2 1 0 0 0;
    1 -2 1 0 0;
    0 1 -2 1 0;
    0 0 1 -2 1;
    0 0 0 1 -2;
]
l = [
    ddy(h)*2*h - u0;
    ddy(h*2)*2*h;
    ddy(h*3)*2*h;
    ddy(h*4)*2*h; - u1;
]
y = K\l

5-element Vector{Float64}:
 27.944444444444446
 50.333333333333336
 61.61111111111111
 56.22222222222223
 28.611111111111114

In [133]:
#2b
ddy(x) = -x
u0 = 0
u1 = 1
h = 10/6
K = [
    -2 1 0 0 0;
    1 -2 1 0 0;
    0 1 -2 1 0;
    0 0 1 -2 1;
    0 0 0 1 -2;
]
l = [
    ddy(h)*2*h - u0;
    ddy(h*2)*2*h;
    ddy(h*3)*2*h;
    ddy(h*4)*2*h; - u1;
]
y = K\l

5-element Vector{Float64}:
 27.944444444444446
 50.333333333333336
 61.61111111111111
 56.22222222222223
 28.611111111111114