In [18]:
#Wesley Mota de Oliviera Gomes
using LaTeXStrings
using Latexify
L"$$
\textbf{Tarefa 4} 
\\\text{ Laboratório - Questões de julia } \\
$$"

LoadError: ArgumentError: Package LaTeXStrings not found in current path:
- Run `import Pkg; Pkg.add("LaTeXStrings")` to install the LaTeXStrings package.


In [19]:
#Pelo método de euler é y(i+1) = y(i)+ h*y'(i)
function euler(y0,x0,h, fd)
    k = x0
    y = y0
    while k < 1
        y = y + h*fd(k, y) #Aplicando euler
        k = k + h #incrementando de h
    end
    return y
end

euler (generic function with 1 method)

In [20]:
#Questão 1 - letra a
fd(x, y) = y
euler(1, 0, 0.1, fd)

2.8531167061100002

In [21]:
#Questão 1 - letra b
fd(x, y) = y^2*x
euler(1, 0, 0.1, fd)

2.0062389840082506

In [22]:
using LinearAlgebra

In [23]:
#Questão 2
function matriz_vandermonde((x0, y0), (x1, y1), (x2, y2), (x3, y3))
    xs = [
            [1 x0 x0^2 x0^3];
            [1 x1 x1^2 x1^3];
            [1 x2 x2^2 x2^3];
            [1 x3 x3^2 x3^3];
        ]
    ys = [[y0],[y1],[y2],[y3]]
    print(xs)
    print("\n")
    print(ys)
    print("\n")
    a = xs\ys
    print(a)
end
a

6-element Vector{Float64}:
  1.001055530820477
 -0.006370457580389344
 -0.4839321422301643
 -0.021779655846211495
  0.05854251257737299
 -0.007213481872945109

In [24]:
matriz_vandermonde((2,3),(5,12),(7,20),(8,25))

[1 2 4 8; 1 5 25 125; 1 7 49 343; 1 8 64 512]
[[3], [12], [20], [25]]


LoadError: MethodError: no method matching one(::Type{Vector{Int64}})
Closest candidates are:
  one(::Union{Type{T}, T}) where T<:AbstractString at strings/basic.jl:262
  one(::Union{Type{P}, P}) where P<:Dates.Period at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Dates/src/periods.jl:54
  one(::AbstractIrrational) at irrationals.jl:151
  ...

In [25]:
using LinearAlgebra
x0 = 2 
y0 = 3
x1 = 5
y1 = 12
x2 = 7
y2 = 20
x3 = 8
y3 = 25

entrada = [(2,3),(5,12),(7,20),(8,25)]
#entrada = [1,23,3]
xs = zeros(length(entrada), length(entrada))
ys = zeros(length(entrada))
for k= 1: length(entrada)
    xn,yn = entrada[k]
    linha = []
    for i = 0:length(entrada)-1
        xs[k, i+1] = xn^i
    end
    ys[k] = yn
end
#xs
a = xs\ys


4-element Vector{Float64}:
 -2.555555555555549
  2.911111111111106
 -0.11111111111111002
  0.02222222222222215

In [26]:
#Questão 3
function matriz_vandermonde_xn(entrada)
    xs = zeros(length(entrada), length(entrada))
    ys = zeros(length(entrada))
    for k= 1: length(entrada)
        xn,yn = entrada[k]
        linha = []
        for i = 0:length(entrada)-1
            xs[k, i+1] = xn^i
        end
        ys[k] = yn
    end
    a = xs\ys
    return a
end

matriz_vandermonde_xn (generic function with 1 method)

In [27]:
matriz_vandermonde_xn([(2,3),(5,12),(7,20),(8,25)])

4-element Vector{Float64}:
 -2.555555555555549
  2.911111111111106
 -0.11111111111111002
  0.02222222222222215

In [28]:
#Questão 4
ddy(x) = 4x
y0 = 5
y10 = 20
h = 10/6
C = [
    -2 1 0 0 0 0;
    1 -2 1 0 0 0;
    0 1 -2 1 0 0;
    0 0 1 -2 1 0;
    0 0 0 1 -2 1;
    0 0 0 0 1 -2
]
b = [
    ddy(h)*2*h - y0;
    ddy(h*2)*2*h;
    ddy(h*3)*2*h;
    ddy(h*4)*2*h;
    ddy(h*5)*2*h;
    ddy(h*6)*2*h - y10;
]
y = C\b

6-element Vector{Float64}:
 -170.63492063492063
 -324.04761904761904
 -433.015873015873
 -475.3174603174604
 -428.73015873015885
 -271.0317460317461

In [29]:
#Exercício 5 - a
entrada = [(-1.2, -5.76),(0.3, -5.61), (1.1, -3.69)]
matriz_vandermonde_xn(entrada)

3-element Vector{Float64}:
 -6.0
  1.0
  1.0000000000000004

In [30]:
#Exercício 5 - b
entrada = [(0.0, 1.225),(3.0, 0.905), (6.0, 0.652)]
matriz_vandermonde_xn(entrada)

3-element Vector{Float64}:
  1.225
 -0.11783333333333336
  0.0037222222222222257

In [31]:
#Exercício 5 - c
entrada = [(0.8,cos(0.8)),(0.9,cos(0.9)),(1.0,cos(1.0)),(1.1,cos(1.1)),(1.2,cos(1.2)),(1.3,cos(1.3))]
a = matriz_vandermonde_xn(entrada)
funcao_interpolada(x) = a[1]+a[2]x+a[3]x^2+a[4]x^3+a[5]x^4+a[6]x^5
funcao_interpolada(1.07)

0.48012422704985785

In [32]:
#Questão 6 - 2a
ddy(x) = -x
u0 = 0
u1 = 1
h = 10/6
C = [
    -2 1 0 0 0;
    1 -2 1 0 0;
    0 1 -2 1 0;
    0 0 1 -2 1;
    0 0 0 1 -2;
]
b = [
    ddy(h)*2*h - u0;
    ddy(h*2)*2*h;
    ddy(h*3)*2*h;
    ddy(h*4)*2*h; - u1;
]
y = C\b

5-element Vector{Float64}:
 27.944444444444446
 50.333333333333336
 61.61111111111111
 56.22222222222223
 28.611111111111114

In [33]:
#Questão 6 - 2b
ddy(x) = -x
u0 = 0
u1 = 1
h = 10/6
C = [
    -2 1 0 0 0;
    1 -2 1 0 0;
    0 1 -2 1 0;
    0 0 1 -2 1;
    0 0 0 1 -2;
]
b = [
    ddy(h)*2*h - u0;
    ddy(h*2)*2*h;
    ddy(h*3)*2*h;
    ddy(h*4)*2*h; - u1;
]
y = C\b

5-element Vector{Float64}:
 27.944444444444446
 50.333333333333336
 61.61111111111111
 56.22222222222223
 28.611111111111114